### PR TITLE
Add support for Dynatrace monitoring

### PR DESCRIPTION
**Pull request by lrgar**
This PR adds a hook for monitoring with the Dynatrace agent on application-only mode, similar to the existing implementations in the Node.js and Static files buildpacks.

This behavior is activated when the user has an attached service with the "dynatrace" substring.

More info about its usage can be found at: https://www.dynatrace.com/support/help/cloud-platforms/cloud-foundry/application-only/deploy-oneagent-on-cloud-foundry-for-application-only-monitoring/

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by Zanadar** [comment]
@lrgar Thanks for the PR. We'll look into this and prioritize.

**Comment by danirabiser** [comment]
Hi @Zanadar, is there anything we can do to address the failing checks? Thanks!

**Comment by Zanadar** [comment]
@danirabiser Looks like this might need to get rebased? That said, I think we can figure out whatever the issues are when we merge. Sorry that this hasn't gotten our attention due to other priorities. We'll at least get it on the team's radar next iteration.

**Comment by dfreilich** [comment]
@lrgar @danirabiser  I added this in `b311e2158ac25807d48324a0fdcc56a72901f4cc`. Thank you for the addition!

**Comment by lrgar** [comment]
Many thanks!

**Pull request closed without merging**
