### PR TITLE
update libbuildpack-dynatrace

### PR DESCRIPTION
**Pull request by arjun024**
This seems to have been turned off in
https://github.com/cloudfoundry/dotnet-core-buildpack/pull/566#issuecomment-1124217592

The util dynatrace app is taken from go buildpack. See https://github.com/cloudfoundry/go-buildpack/pull/266 and https://github.com/cloudfoundry/go-buildpack/pull/276

---

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

### CODE REVIEW

**Comment by arjun024** [comment]
@arthfl Could you take a look? I'm unable to add you as a reviewer

**Comment by arthfl** [comment]
@arjun024 Looks ok on quick glance.
But i'd suggest you wait a bit until we release the next version of libbuildpack-dynatrace, since i'm currently working on a fix for a bug in there.

**Comment by arthfl** [comment]
@arjun024 please use v1.5.1, i just released it.
This contains the bugfix.

**Comment by arjun024** [comment]
@arthfl I have updated go.mod to the 1.5.1

**Comment by brayanhenao** [comment]
@arthfl Any update on this?

**Comment by ForestEckhardt** [comment]
Checking for an update here.

**Comment by arjun024** [comment]
I have updated the PR to reflect the latest 1.5.2.

**Comment by sophiewigmore** [comment]
Thank you @arjun024! 
@arthfl or @rbamberger when you have a chance, could you check out this PR and make sure it looks OK?

**Comment by arthfl** [comment]
@sophiewigmore Looks good to me.

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
